---
envs:
  - MICROCI_DISCORD_WEBHOOK: https://discord.com/api/webhooks/943613047375802470/sG8Esn7vuKfgqywFf2Uc30ISQLQDl__GffglPGQ5nxySNVHwApRiWL6KW8XOcw7NO-Si 
steps:
  - name: "Gerar relatório de verificação do código C++ clang-tidy"
    description: "Verifica o código C++ e gera relatório em formato HTML"
    # only: "clang-tidy"
    plugin:
      name: "clang-tidy"
      options:
        - "-std=c++17"
      include:
        - "/usr/include/"
      source:
        - "src/*pp"
        - "test/*pp"
  - name: "Gerar relatório de verificação do código C++ cppcheck"
    # only: "cppcheck"
    plugin:
      name: "cppcheck"
      include:
        - "include"
      source:
        - "src"
        - "test"
      platform: "unix64"
      std: "c++17"
  - name: "Construir documentação em formato HTML"
    description: "Documentação do projeto"
    plugin:
      name: "mkdocs_material"
      action: "build"
  - name: "Configurar github pages"
    description: "Configura domínio Apex para github pages, arquivo README e ajusta usuário"
    bash: |
      cp github-pages/CNAME site/
      cat docs/index.md > README.md
      # Apenas para disponibilizar uma página de rosto para o github
      cp README.md site/
      chown $(id -u).$(id -g) -Rv site/
  - name: "Publicar documentação em microci.dev"
    # only: "publish"
    ssh:
    plugin:
      name: "git_publish"
      git_url: "git@github.com:geraldolsribeiro/microci.dev.git"
  - name: "Servidor local na porta 8000 (Ctrl+C para finalizar)"
    description: "Executa servidor local para preview da documentação"
    only: "serve"
    plugin:
      name: "mkdocs_material"
      action: "serve"
  - name: "Compilar versão estática do microCI"
    docker: "gcc:11"
    run_as: root
    bash: |
      apt update
      apt upgrade -y
      apt install -y xxd libspdlog-dev libyaml-cpp-dev
      make -C src clean all
      make -C test
      chown $(id -u).$(id -g) -Rv src/microCI

# vim: spell spelllang=pt,en
