packet
title iperf 2 Ethernet frame: 1468 payload + 8B UDP + 20B IP + 14B + 4B = 1514B
+24: "MAC Destination"
+24: "MAC Source"
+16: "Type"
+4: "IP version"
+4: "Header lenght"
+8: "Type of Service"
+16: "Total lenght (header + data)"
+16: "Identification"
+3: "Flags"
+13: "Fragment offset"
+8: "Time to live"
+8: "Protocol"
+16: "Header checksum"
+32: "Source IP"
+32: "Destination IP"
+16: "UDP Source port"
+16: "UDP Destination port"
+16: "UDP Lenght"
+16: "UDP Checksum"
+32: "IPERF Second"
+32: "IPERF Microsecond"
+32: "IPERF Packet ID"
+128: "IPERF Random data 1468"
+32: "Ethernet Frame Check Sequence"
