---
name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y xxd libspdlog-dev libyaml-cpp-dev libcrypto++-dev gettext
    - name: download headers
      run: |
        mkdir -p include/nlohmann
        wget -P include https://raw.githubusercontent.com/adishavit/argh/master/argh.h
        wget -P include https://raw.githubusercontent.com/pantor/inja/master/single_include/inja/inja.hpp
        wget -P include https://raw.githubusercontent.com/Rookfighter/inifile-cpp/master/include/inicpp.h
        wget -P include/nlohmann https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp
    - name: make
      run: make -C src clean all
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: microCI
        path: bin/microCI
        retention-days: 5
    - name: 'Pre-Release'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          bin/microCI
          LICENSE
