name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y xxd libspdlog-dev libyaml-cpp-dev libcrypto++-dev gettext
    - name: download headers
      run: wget -P include https://raw.githubusercontent.com/adishavit/argh/master/argh.h
      run: wget -P include https://raw.githubusercontent.com/pantor/inja/master/single_include/inja/inja.hpp
      run: wget -P include https://raw.githubusercontent.com/Rookfighter/inifile-cpp/master/include/inicpp.h
      run: wget -P include/nlohmann https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp
    - name: make
      run: make -C src clean all
